### PR TITLE
add examples in an example file

### PR DESCRIPTION
**Pull request by SimonWaldherr**
add examples as described in https://blog.golang.org/examples

### CODE REVIEW

**Comment by SimonWaldherr** [comment]
many thanks for this great package

**Comment by SimonWaldherr** [comment]
ping @mikejewell 🙂

**Comment by SimonWaldherr** [comment]
FYI: I added it also to my [SimonWaldherr/golang-examples](https://github.com/SimonWaldherr/golang-examples)-Repo: https://github.com/SimonWaldherr/golang-examples/blob/master/non-std-lib/timeseries.go

and to this gist: https://gist.github.com/SimonWaldherr/bdcfbd2dcfa9f1fd91be0496979b71bb

**Comment by mikejewell** [comment]
That's great - thanks @SimonWaldherr! Glad to see it coming in handy :)

**Pull request merged**
